export enum BookEvent {
	CREATE_BOOK = "BOOK_CREATE",
	GET_ALL_BOOKS = "BOOK_GET_ALL",
	GET_BOOK_BY_ID = "BOOK_GET_BY_ID",
	UPDATE_BOOK = "BOOK_UPDATE",

	SOFT_DELETE_BOOK = "BOOK_SOFT_DELETE",
	RESTORE_BOOK = "BOOK_RESTORE",

	HARD_DELETE_BOOK = "BOOK_HARD_DELETE",
}
