export enum BookEvent {
	CREATE_BOOK = "BOOK_CREATE",
	GET_ALL_BOOKS = "BOOK_GET_ALL",
	GET_BOOK_BY_ID = "BOOK_GET_BY_ID",
	UPDATE_BOOK = "BOOK_UPDATE",

	SOFT_DELETE_BOOK = "BOOK_SOFT_DELETE",
	RESTORE_BOOK = "BOOK_RESTORE",

	HARD_DELETE_BOOK = "BOOK_HARD_DELETE",
}

export enum AuthEvent {
	USER_REGISTER = "AUTH_REGISTER_ATTEMPT",
	USER_LOGIN = "AUTH_LOGIN_ATTEMPT",
	PASSWORD_FORGOT_REQUEST = "AUTH_PASSWORD_FORGOT_REQUEST",
	PASSWORD_RESET = "AUTH_PASSWORD_RESET_ATTEMPT",

	USER_LOGOUT = "AUTH_LOGOUT",
	USER_PROFILE_VIEW = "AUTH_PROFILE_VIEW",
	PASSWORD_CHANGE = "AUTH_PASSWORD_CHANGE_ATTEMPT",
	TOKEN_REFRESH = "AUTH_TOKEN_REFRESH_ATTEMPT",
}

export enum CategoryEvent {
	CATEGORY_CREATE = "CATEGORY_CREATE",
	CATEGORY_GET_ALL = "CATEGORY_GET_ALL",
	CATEGORY_GET_BY_ID = "CATEGORY_GET_BY_ID",
	CATEGORY_UPDATE = "CATEGORY_UPDATE",
	CATEGORY_DELETE = "CATEGORY_DELETE",
}

export enum UserManagementEvent {
	ADMIN_GET_ALL_USERS = "ADMIN_GET_ALL_USERS",
	ADMIN_GET_USER_BY_ID = "ADMIN_GET_USER_BY_ID",
	ADMIN_CREATE_USER = "ADMIN_CREATE_USER",
	ADMIN_UPDATE_USER = "ADMIN_UPDATE_USER",
	ADMIN_DELETE_USER = "ADMIN_DELETE_USER",
}
